apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ .Values.podMonitor.clusterOperatorMetrics.name }}
  namespace : {{ .Values.podMonitor.namespace }}
  labels: {{ toYaml .Values.podMonitor.labels | nindent 4 }}
spec:
  selector:
    matchLabels: {{ toYaml .Values.podMonitor.clusterOperatorMetrics.selector.matchLabels | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Values.kafka.namespace }}
  podMetricsEndpoints:
  - path: /metrics
    port: http
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ .Values.podMonitor.entityOperatorMetrics.name }}
  namespace : {{ .Values.podMonitor.namespace }}
  labels: {{ toYaml .Values.podMonitor.labels | nindent 4 }}
spec:
  selector:
    matchLabels: {{ toYaml .Values.podMonitor.entityOperatorMetrics.selector.matchLabels | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Values.kafka.namespace }}
  podMetricsEndpoints:
  - path: /metrics
    port: healthcheck

---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ .Values.podMonitor.kafkaResourcesMetrics.name }}
  namespace : {{ .Values.podMonitor.namespace }}
  labels: {{ toYaml .Values.podMonitor.labels | nindent 4 }}
spec:
  selector:
    matchExpressions: {{ toYaml .Values.podMonitor.kafkaResourcesMetrics.selector.matchExpressions | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Values.kafka.namespace }}
  podMetricsEndpoints:
  - path: /metrics
    port: tcp-prometheus
    relabelings:
    - separator: ;
      regex: __meta_kubernetes_pod_label_(strimzi_io_.+)
      replacement: $1
      action: labelmap
    - sourceLabels: [__meta_kubernetes_namespace]
      separator: ;
      regex: (.*)
      targetLabel: namespace
      replacement: $1
      action: replace
    - sourceLabels: [__meta_kubernetes_pod_name]
      separator: ;
      regex: (.*)
      targetLabel: kubernetes_pod_name
      replacement: $1
      action: replace
    - sourceLabels: [__meta_kubernetes_pod_node_name]
      separator: ;
      regex: (.*)
      targetLabel: node_name
      replacement: $1
      action: replace
    - sourceLabels: [__meta_kubernetes_pod_host_ip]
      separator: ;
      regex: (.*)
      targetLabel: node_ip
      replacement: $1
      action: replace